# port
server:
  port: 8081

# db
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pet_health
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

data:
  path: F:/dev/source/res/
